default_install_hook_types: [
  pre-commit, pre-merge-commit, pre-push,
  post-checkout, post-commit]
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
exclude: (^tests/.*/.*$)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: local
  hooks:
    - id: static-checks
      name: static-checks
      description: >-
        This hook runs all static checks, including mypy, and ruff.
        It is recommended to run this on pre-commit and pre-push.
        Will also sync and update the uv.lock file before commit.
      always_run: true
      language: python
      entry: uv run tox -m static

    - id: update-version
      name: update-version
      description: >-
        This hook uses the hatch-vcs module to update the `_version.py` file.
        Call this on post-commit and post-checkout.
      stages: [post-commit, post-checkout, manual]
      always_run: true
      language: python
      pass_filenames: false
      entry: uv run --frozen hatch build --hooks-only
