default_install_hook_types: [pre-commit, pre-merge-commit, pre-push]
default_stages: [pre-commit, pre-merge-commit, pre-push, manual]
exclude: (^tests/.*/.*$)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.6.13
  hooks:
    - id: uv-lock  # Ensure lockfile is up to date
    - id: uv-export  # Export the lockfile to requirements.txt
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.4
  hooks:
    - id: ruff
      args: [ --no-fix]
      always_run: true
    - id: ruff-format
      always_run: true

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: uv run mypy
      always_run: true
      language: python
      types: [python]
