name: Publish and Release

#   A github reusable workflow to:
#   - Run code checks and tests on multiple python versions and platforms;
#   - Publish a python package to test.pypi.org and pypi.org; and
#   - Create a GitHub Release.
#
#   The workflow is triggered on:
#   - push to version tags matching "v*", eg. "v1.0.0", or
#   - manual workflow_dispatch (eg. from the github `Actions` tab):
#     - will produce a release with a version tag like: "v1.0.1.devN"
#
#   Uses reusable workflows from the <https://github.com/glenn20/python-ci>
#   repository.

on:
  push:
    tags: ["v*"]  # Publish on tags matching "v*", eg. "v1.0.0"
  workflow_dispatch:

jobs:
  checks:
    name: Code checks
    uses: glenn20/python-ci/.github/workflows/check.yaml@v1

  build:
    name: Build
    uses: glenn20/python-ci/.github/workflows/build.yaml@v1

  publish-test:
    name: Publish to test.pypi
    uses: ./.github/workflows/publish.yaml
    needs: build
    with:
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  publish-pypi:
    name: Publish to pypi
    uses: ./.github/workflows/publish.yaml
    needs: build
    with:
      pypi: upload.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!

  github-release:
    name: Create GitHub release
    uses: glenn20/python-ci/.github/workflows/release.yaml@v1
    needs: build
    permissions:
      contents: write  # IMPORTANT: mandatory for github release
      id-token: write  # IMPORTANT: mandatory for github release
