name: Test and Build

# Run the code checks and CI pytest workflow on
# - push to `main` or `dev` branches, or
# - manually triggered from github Actions tab.

# Build and publish to test.pypi on
# - push to `main` branch.

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: CI tests (full)
    uses: glenn20/python-ci/.github/workflows/ci-tox.yaml@dev
    with:
      os: '["ubuntu-latest"]'  # CI tests only run on linux
      python-version: '["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]'

  publish-test:
    name: Publish to test.pypi
    needs: tests
    uses: ./.github/workflows/publish.yaml
    with:
      pypi: test.pypi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing!
